---
# defaults file for liquibase
# namespace is lb_*

######################
# Required properties
######################

# Required
lb_deploy_scripts_user: "{{ deploy_scripts_user | default('runner') }}"
lb_app_artifactory_url: "{{ app_artifactory_url | default('https://bwa.nrs.gov.bc.ca/pub/artifactory') }}"

lb_liquibase_staging_dir:  "{{ cd_app_home }}/liquibase"
lb_liquibase_library_dir:  "{{ lb_liquibase_staging_dir }}/lib"
lb_liquibase_version: "{{ liquibase_version | default('4.5.0') }}"
lb_liquibase_download_url: "https://github.com/liquibase/liquibase/releases/download/v{{lb_liquibase_version}}/liquibase-{{lb_liquibase_version}}.tar.gz"

cd_migrations_base_dir: "{{ migrations_base_dir | default('cd/migrations') }}"
lb_working_dir: "{{ cd_app_home }}/{{ working_dir | default(cd_migrations_base_dir+'/'+db_username) }}"
lb_log_level: "{{ log_level | default('info') }}"
lb_iitd_core_dir: "{{ iitd_core_dir | default('/apps_ux/FFS/ffs-db/cd/migrations/nrdk') }}"

lb_changelog_file: "{{ changelog_file | default('changelog.xml') }}"
lb_db_url: "{{ db_url }}"
lb_db_username: "{{ db_username }}"
lb_db_password: "{{ db_password }}"
lb_actions: "{{ (db_actions | default('migrate')).split(',') }}"

lb_migrations_artifact:
  group_id: "{{ artifact_group_id }}"
  artifact_id: "{{ artifact_id }}"
  type: "{{ artifact_type }}"
  classifier: "{{ artifact_classifier }}"
  version: "{{ cd_version }}"
  name: "{{ artifact_id+'-'+cd_version+'-'+artifact_classifier+'.'+artifact_type }}"


lb_overwrite_baseline: "{{ overwrite_baseline | default(False) }}"