---
- name: Check app variable
  assert:
    that:
      - app | default('') | length > 0 
    msg: 'app variable must not be empty'

- name: Check component variable
  assert:
    that:
      - component | default('') | length > 0 
    msg: 'component variable must not be empty'

- name: Check for fluent-bit service
  stat:
    path: /apps_ux/s6_services/fluent-bit/run
  register: fluent_bit_run
  become: yes
  become_user: wwwadm
  tags:
  - delete-app

- name: Stop fluent-bit
  include_role:
    name: tomcat_stop
    apply:
      tags: [delete-app]
  when: fluent_bit_run.stat.exists
  tags:
  - delete-app

- name: Create app conf directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0775'
  loop:
    - '{{ apm_agent_home }}/conf/{{ app | lower }}-{{ component | lower }}'
    - '{{ apm_agent_home }}/conf/{{ app | lower }}-{{ component | lower }}/filter'
    - '{{ apm_agent_home }}/conf/{{ app | lower }}-{{ component | lower }}/input'
    - '{{ apm_agent_home }}/conf/{{ app | lower }}-{{ component | lower }}/parser'
    - '{{ apm_agent_home }}/db/fluent-bit-logs-{{ app | lower }}-{{ component | lower }}'
  become: yes
  become_user: wwwadm

- name: Configuration files
  template:
    src: 'templates/{{ item }}'
    dest: '{{ apm_agent_home }}/conf/{{ app | lower }}-{{ component | lower }}/{{ item }}'
    mode: '0664'
  loop:
    - filter/filters.conf
    - input/inputs.conf
    - parser/parsers.conf
  become: yes
  become_user: wwwadm

- name: Remove component config
  file:
    state: absent
    path: '{{ apm_agent_home }}/conf/{{ app | lower }}-{{ component | lower }}'
  become: yes
  become_user: wwwadm
  tags:
  - never
  - delete-app

- name: Start fluent-bit
  include_role:
    name: tomcat_start
    apply:
      tags: delete-app
  when: fluent_bit_run.stat.exists
  tags:
  - molecule-notest
  - delete-app
